### ISSUE TITLE
Ahrefs

### ISSUE THREAD

**Issue by benmonopoli** [EuropeanRemote/european-remote-software-companies#8]
Hello, info in Ahrefs is incorrect

- Headquarters stated as US - Should be Singapore 
- Company Size 100 - 150
- Places Hiring Globally (if that's an option)
- Backend - Remove Rust - Add DLang
- Frontend - Add Melange
- Comp and bens - Yes for - Equipment Budget, Team. Gatherings, Fleible working hours, Conference budget,

**Comment by imaginalis** [comment]
Hey @benmonopoli thanks for the insights. 

Will prepare the PR and ping you here 👍

**Comment by imaginalis** [comment]
The list update: https://github.com/EuropeanRemote/european-remote-software-companies/commit/59c18fda8868ac983006744308eafd78e9c024c8 

The company profile has also been updated 👍
